## Pandas Cookbook 
see: https://pandas.pydata.org/docs/user_guide/index.html

In [4]:
import numpy as np
import pandas as pd

## Generate new pandas objects
Two main data structures in pandas:  
* Series = 1-dimensional iteratable such as a list of integers, a dictionary of strings, an array of objects, etc...
* DataFrame - 2-dimensional that works like a table with rows and columns

### Series examples

In [141]:
# generate a series
int_series_data = pd.Series([1, 5, 5, np.nan, 6, 8])
int_series_data

0    1.0
1    5.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [142]:
# generate string series
str_series_data = pd.Series(["this", "is", "a", "string", "series", "it", "can", "contain", "duplicates", "duplicates", "count", "the", "dups", "duplicates"])
str_series_data

0           this
1             is
2              a
3         string
4         series
5             it
6            can
7        contain
8     duplicates
9     duplicates
10         count
11           the
12          dups
13    duplicates
dtype: str

In [143]:
# generate string series
# index equates to row names
str_series_data = pd.Series(["this", "is", "a", "string", "series", "it", "can", "contain", "duplicates", "duplicates", "count", "the", "dups", "duplicates"], 
                            index=["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n"])
str_series_data

a          this
b            is
c             a
d        string
e        series
f            it
g           can
h       contain
i    duplicates
j    duplicates
k         count
l           the
m          dups
n    duplicates
dtype: str

In [144]:
# generate string series
# index equates to row names - DO NOT NEED TO BE UNIQUE!
str_series_data = pd.Series(["this", "is", "a", "string", "series", "it", "can", "contain", "duplicates", "duplicates", "count", "the", "dups", "duplicates"], 
                            index=["a", "a", "a", "a", "e", "f", "g", "h", "c", "j", "k", "l", "b", "c"])
str_series_data

a          this
a            is
a             a
a        string
e        series
f            it
g           can
h       contain
c    duplicates
j    duplicates
k         count
l           the
b          dups
c    duplicates
dtype: str

### Dataframe example

In [145]:
# generate dataframes 
# date_range() produces a numpy array
dates_df = pd.date_range(start = "20130101", 
                         periods=6, 
                         freq="D",     
                         inclusive="both")
dates_df

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [191]:
# generate data frame by dictionary
df2_nonamed_index = pd.DataFrame(data= {
     "A": 1.0,
     "B": pd.Timestamp("20130102"),
     "C": pd.Series(1, index = range(8), dtype = "float32"),
     "D": np.array([3] * 8, dtype = "int32"),
     "E": pd.Categorical(values=["test", "train", "test", "train", "test", "train", "test", "train"]),
     "F": "foo"
     }
)
df2_nonamed_index

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo
4  1.0 2013-01-02  1.0  3   test  foo
5  1.0 2013-01-02  1.0  3  train  foo
6  1.0 2013-01-02  1.0  3   test  foo
7  1.0 2013-01-02  1.0  3  train  foo

In [147]:
# generate data frame by dictionary
# now add index (row names)
df2 = pd.DataFrame(data= {
     "A": 1.0,
     "B": pd.Timestamp("20130102"),
     "C": pd.Series(1, index = range(4), dtype = "float32"),
     "D": np.array([3] * 4, dtype = "int32"),
     "E": pd.Categorical(values=["test", "train", "test", "train"]),
     "F": "foo"
     },index=['sample {}'.format(num) for num in range(1,5)]
)
df2

            A          B   C  D      E    F
sample 1  1.0 2013-01-02 NaN  3   test  foo
sample 2  1.0 2013-01-02 NaN  3  train  foo
sample 3  1.0 2013-01-02 NaN  3   test  foo
sample 4  1.0 2013-01-02 NaN  3  train  foo

In [11]:
# generate data frame by dictionary
# now add index (row names) - DOES NOT NEED TO BE UNIQUE!!
df2 = pd.DataFrame(data= {
     "A": 1.0,
     "B": pd.Timestamp("20130102"),
     "C": pd.Series(1, index = range(7), dtype = "float32"),
     "D": np.array([3] * 7, dtype = "int32"),
     "E": pd.Categorical(values=["test", "train", "unknown", "train", "train", "test", "test"]),
     "F": "foo",
     "G": np.random.randint(low = -5, high = 7, size = 7),
     "H": np.random.ranf(size = 7),
     "I": [True, False, False, False, False, True, True]
     },
     index=["sample 1", "sample 2", "sample 1", "sample 2", "sample 3", "sample 4", "sample 5"]
)
df2

            A          B   C  D        E    F  G         H      I
sample 1  1.0 2013-01-02 NaN  3     test  foo  2  0.135307   True
sample 2  1.0 2013-01-02 NaN  3    train  foo  1  0.447303  False
sample 1  1.0 2013-01-02 NaN  3  unknown  foo  0  0.954773  False
sample 2  1.0 2013-01-02 NaN  3    train  foo -1  0.477295  False
sample 3  1.0 2013-01-02 NaN  3    train  foo  3  0.886016  False
sample 4  1.0 2013-01-02 NaN  3     test  foo -3  0.070618   True
sample 5  1.0 2013-01-02 NaN  3     test  foo  0  0.893761   True

In [ ]:
# print column "A"
df2.A

sample 1     True
sample 2    False
sample 1    False
sample 2    False
sample 3    False
sample 4     True
sample 5     True
Name: I, dtype: bool

In [150]:
# axis = 0 (rows), axis = 1 (columns)
# count the number of non-NaN entries in each row
# in pandas, NaN, NaT, None, pandas.NA are all considered as NA
df2.count(axis = 0) 

# the results below would indicate that for column "C" all rows(index in our case samples) are all NaN/NA/NaT/None and that column "A", has 7 rows(samples in our case) values that are not NA

A    7
B    7
C    0
D    7
E    7
F    7
G    7
H    7
dtype: int64

In [151]:
# axis = 0 (rows), axis = 1 (columns)
# count the number of non-NaN, non-NaT, non-None, non-NA entries in each column
# in pandas, NaN, NaT, None, pandas.NA are all considered as NA
df2.count(axis = 1, numeric_only = False)

# the results below would indicate that 7 columns in the first occurence of "sample 1" row/index (sample in our case) all contain values that are not NA
# as a matter of fact, all samples (rows) have 7 columns that don't contain NA.  This is true because we have 8 columns, and we know column "C" is NA for all rows

sample 1    7
sample 2    7
sample 1    7
sample 2    7
sample 3    7
sample 4    7
sample 5    7
dtype: int64

## Viewing contents in pandas objects
* `.head()`
* `.tail()`
* `.index`
* `.to_numpy()`
* `.dtypes`
* `.describe()`
* `.T`
* `.sort_index()`
* `.sort_values()`

In [152]:
# view first 10 rows/indices
df2.head(3)

            A          B   C  D      E    F  G         H
sample 1  1.0 2013-01-02 NaN  3   test  foo -5  0.759492
sample 2  1.0 2013-01-02 NaN  3  train  foo -4  0.227645
sample 1  1.0 2013-01-02 NaN  3   test  foo  1  0.991933

In [153]:
# view the last row/index
df2.tail(1)

            A          B   C  D     E    F  G         H
sample 5  1.0 2013-01-02 NaN  3  test  foo -5  0.798241

In [154]:
# show the row names of the data frame (indices/index)
df2.index

Index(['sample 1', 'sample 2', 'sample 1', 'sample 2', 'sample 3', 'sample 4',
       'sample 5'],
      dtype='str')

In [155]:
# view data frame as a numpy array with rows(indices) and columns stripped off
# the dtype is inferred from the pandas dataframe.  However, since pandas allows each column to have a dtype, numpy can only handle
# a single dtype for the whole array, so numpy automatically infers the dtype based on the minimum type that can cover all types in the
# dataframe
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), nan, 3, 'test', 'foo', -5,
        0.7594916775769114],
       [1.0, Timestamp('2013-01-02 00:00:00'), nan, 3, 'train', 'foo',
        -4, 0.22764473299501498],
       [1.0, Timestamp('2013-01-02 00:00:00'), nan, 3, 'test', 'foo', 1,
        0.9919328187670363],
       [1.0, Timestamp('2013-01-02 00:00:00'), nan, 3, 'train', 'foo', 6,
        0.0784449914921167],
       [1.0, Timestamp('2013-01-02 00:00:00'), nan, 3, 'train', 'foo', 5,
        0.5753263258649501],
       [1.0, Timestamp('2013-01-02 00:00:00'), nan, 3, 'test', 'foo', 1,
        0.7167249303691777],
       [1.0, Timestamp('2013-01-02 00:00:00'), nan, 3, 'test', 'foo', -5,
        0.7982409162862927]], dtype=object)

In [156]:
# view the type for each column in the data frame
df2.dtypes

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
G             int64
H           float64
dtype: object

In [157]:
# calculate and quickly view the summary statistics for a particular column in the data frame
df2.A.describe()

count    7.0
mean     1.0
std      0.0
min      1.0
25%      1.0
50%      1.0
75%      1.0
max      1.0
Name: A, dtype: float64

In [158]:
# calculate and quickly view the summary statistics for a particular column in the data frame
df2.G.describe()

count    7.000000
mean    -0.142857
std      4.634241
min     -5.000000
25%     -4.500000
50%      1.000000
75%      3.000000
max      6.000000
Name: G, dtype: float64

In [159]:
# view the dataframe after transposing the dataframe; columns become indices (rows) and rows (indices) become columns
df2.T

,sample 1,sample 2,sample 1,sample 2,sample 3,sample 4,sample 5
A,1.0,1.0,1.0,1.0,1.0,1.0,1.0
B,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00
C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
D,3,3,3,3,3,3,3
E,test,train,test,train,train,test,test
F,foo,foo,foo,foo,foo,foo,foo
G,-5,-4,1,6,5,1,-5
H,0.759492,0.227645,0.991933,0.078445,0.575326,0.716725,0.798241

In [160]:
# view the dataframe after it is sorted
# sort by rows (axis=0)
# which row index do you want to sort by; default is 0/None, however, if you have mutliple indices levels, you can choose which one to base the sort on
df2.sort_index(axis=0, level = 0, ascending= True, kind = 'quicksort', inplace=False)

            A          B   C  D      E    F  G         H
sample 1  1.0 2013-01-02 NaN  3   test  foo -5  0.759492
sample 1  1.0 2013-01-02 NaN  3   test  foo  1  0.991933
sample 2  1.0 2013-01-02 NaN  3  train  foo -4  0.227645
sample 2  1.0 2013-01-02 NaN  3  train  foo  6  0.078445
sample 3  1.0 2013-01-02 NaN  3  train  foo  5  0.575326
sample 4  1.0 2013-01-02 NaN  3   test  foo  1  0.716725
sample 5  1.0 2013-01-02 NaN  3   test  foo -5  0.798241

In [161]:
# sorts row (indices) by column G in descending order
df2.sort_values(by = "G", ascending=False)

            A          B   C  D      E    F  G         H
sample 2  1.0 2013-01-02 NaN  3  train  foo  6  0.078445
sample 3  1.0 2013-01-02 NaN  3  train  foo  5  0.575326
sample 1  1.0 2013-01-02 NaN  3   test  foo  1  0.991933
sample 4  1.0 2013-01-02 NaN  3   test  foo  1  0.716725
sample 2  1.0 2013-01-02 NaN  3  train  foo -4  0.227645
sample 1  1.0 2013-01-02 NaN  3   test  foo -5  0.759492
sample 5  1.0 2013-01-02 NaN  3   test  foo -5  0.798241

In [162]:
# sorts row (indices) by column G in descending order
# can sort by multiple columns
# doesn't change because column D is all the same values but it would perform a second sort on col D
df2.sort_values(by = ["G", "D"], ascending=False)

            A          B   C  D      E    F  G         H
sample 2  1.0 2013-01-02 NaN  3  train  foo  6  0.078445
sample 3  1.0 2013-01-02 NaN  3  train  foo  5  0.575326
sample 1  1.0 2013-01-02 NaN  3   test  foo  1  0.991933
sample 4  1.0 2013-01-02 NaN  3   test  foo  1  0.716725
sample 2  1.0 2013-01-02 NaN  3  train  foo -4  0.227645
sample 1  1.0 2013-01-02 NaN  3   test  foo -5  0.759492
sample 5  1.0 2013-01-02 NaN  3   test  foo -5  0.798241

## Selecting and Subsetting Data  
* Getitem (`[]`) - good for rearranging order of columns in a dataframe
* slicing (`:`) - good for selecting rows/indices
* by label (`.loc[]` or `.at[]`)
* by position (`.iloc[]` or `.iat[]`)
* boolean indexing (`>`, `<`, `>=`, `<=`, `==`, `&`, `|`, `.isin()`, `.query()`)
* keep original shape but show where (`.where()`) or mask values (`.mask()`)
* setting/updating

### Example: Getitem (`[]`) - good for rearranging order of columns in a dataframe

In [267]:
# This will return a series for what is listed in column E
# df2["E"] and df2.E are equivalent, the main difference is the .E version can only be used if your columns only contain letter, numbers and underscores
# if you have spaces or special characters then the GetItem (["E"]) approach as shown below must be used
df2["E"]

sample 1       test
sample 2      train
sample 1    unknown
sample 2      train
sample 3      train
sample 4       test
sample 5       test
Name: E, dtype: category
Categories (3, str): ['test', 'train', 'unknown']

In [268]:
# select columns G, A, and B and rearrange them in the same order provided
df2[["G", "A", "B"]]

          G     A          B
sample 1  1  16.0 2013-01-02
sample 2 -5  10.0 2013-01-02
sample 1  6  16.0 2013-01-02
sample 2  4  16.0 2013-01-02
sample 3  4  16.0 2013-01-02
sample 4 -2  16.0 2013-01-02
sample 5  4  10.0 2013-01-02

### Example: slicing (`:`) - good for selecting rows/indices

In [269]:
# select the first two rows of the data frame
# note, the last number is non-inclusive and as with python, dataframes are 0-indexed
df2[0:2]

,A,B,C,D,E,F,G,H,phenotype,"(sample 4, C)"
sample 1,16.0,2013-01-02,NaN,5,test,foo,1,0.086815,NaN,3
sample 2,10.0,2013-01-02,NaN,3,train,foo,-5,0.731428,NaN,3

In [270]:
# select the last 3 rows
df2[df2.shape[0]-3:df2.shape[0]]

,A,B,C,D,E,F,G,H,phenotype,"(sample 4, C)"
sample 3,16.0,2013-01-02,NaN,3,train,foo,4,0.050358,NaN,3
sample 4,16.0,2013-01-02,3.0,3,test,foo,-2,0.072346,NaN,3
sample 5,10.0,2013-01-02,NaN,3,test,foo,4,0.798816,NaN,3

### Example: by label (`.loc[]` or `.at[]`)

In [271]:
# subset to all rows of columns E and G only
df2.loc[:, ["E", "G"]]

                E  G
sample 1     test  1
sample 2    train -5
sample 1  unknown  6
sample 2    train  4
sample 3    train  4
sample 4     test -2
sample 5     test  4

In [272]:
# subset to rows called "sample 1" and of columns E and G only
df2.loc["sample 1", ["E", "G"]]

                E  G
sample 1     test  1
sample 1  unknown  6

In [273]:
# subset to rows called "sample 1" and "sample 2" and of columns E and G only
df2.loc[["sample 1", "sample 2"], ["E", "G"]]

                E  G
sample 1     test  1
sample 1  unknown  6
sample 2    train -5
sample 2    train  4

In [274]:
# For getting fast access to a scalar (equivalent to the prior method)
# but for single scalar values this is fastest
df2.at["sample 5", "G"]

np.int64(4)

### Example: by position (`.iloc[]` or `.iat[]`)

In [275]:
# select first 2 rows and 4th row, but keep all columns
df2.iloc[[0,1,3],:]

,A,B,C,D,E,F,G,H,phenotype,"(sample 4, C)"
sample 1,16.0,2013-01-02,NaN,5,test,foo,1,0.086815,NaN,3
sample 2,10.0,2013-01-02,NaN,3,train,foo,-5,0.731428,NaN,3
sample 2,16.0,2013-01-02,NaN,3,train,foo,4,0.213125,NaN,3

In [276]:
# keep all rows but select first 3 columns
df2.iloc[:,0:3]

             A          B    C
sample 1  16.0 2013-01-02  NaN
sample 2  10.0 2013-01-02  NaN
sample 1  16.0 2013-01-02  NaN
sample 2  16.0 2013-01-02  NaN
sample 3  16.0 2013-01-02  NaN
sample 4  16.0 2013-01-02  3.0
sample 5  10.0 2013-01-02  NaN

In [277]:
# get value of cell at index 1 (2nd row) and column index 7 (8th column)
df2.iloc[1,7]

np.float64(0.7314275625912108)

In [278]:
# get value of cell at index 1 (2nd row) and column index 7 (8th column)
# faster access for singular scalar value
df2.iat[1,7]

np.float64(0.7314275625912108)

### boolean indexing (`>`, `<`, `>=`, `<=`, `==`, `&`, `|`, `.isin()`, `.query()`)

In [299]:
# select all rows where G is negative
df2[df2['G'] < 0]

,A,B,C,D,E,F,G,H,phenotype,"(sample 4, C)"
sample 2,10.0,2013-01-02,NaN,3,train,foo,-5,0.731428,NaN,3
sample 4,32.0,2013-01-02,3.0,3,test,foo,-2,0.072346,NaN,3

In [300]:
# select all rows where G is negative and H is greater than or equal to 0.50
df2[(df2['G'] < 0) & (df2['H'] >= 0.50)]

,A,B,C,D,E,F,G,H,phenotype,"(sample 4, C)"
sample 2,10.0,2013-01-02,NaN,3,train,foo,-5,0.731428,NaN,3

In [301]:
# select all rows where E is equal to "train"
df2[(df2['E'] == "train")]

,A,B,C,D,E,F,G,H,phenotype,"(sample 4, C)"
sample 2,10.0,2013-01-02,NaN,3,train,foo,-5,0.731428,NaN,3
sample 2,32.0,2013-01-02,NaN,3,train,foo,4,0.213125,NaN,3
sample 3,32.0,2013-01-02,NaN,3,train,foo,4,0.050358,NaN,3

In [ ]:
# select all rows where E is not equal to "train"
df2[(df2['E'] != "train")]

,A,B,C,D,E,F,G,H,phenotype,"(sample 4, C)"
sample 1,32.0,2013-01-02,NaN,5,test,foo,1,0.086815,NaN,3
sample 1,32.0,2013-01-02,NaN,3,unknown,foo,6,0.120409,NaN,3
sample 4,32.0,2013-01-02,3.0,3,test,foo,-2,0.072346,NaN,3
sample 5,10.0,2013-01-02,NaN,3,test,foo,4,0.798816,NaN,3

In [21]:
# select all rows where I is False (~ negates the default of True )
df2.loc[~df2['I']]

            A          B   C  D        E    F  G         H      I
sample 2  1.0 2013-01-02 NaN  3    train  foo  1  0.447303  False
sample 1  1.0 2013-01-02 NaN  3  unknown  foo  0  0.954773  False
sample 2  1.0 2013-01-02 NaN  3    train  foo -1  0.477295  False
sample 3  1.0 2013-01-02 NaN  3    train  foo  3  0.886016  False

In [20]:
# select all rows where I is True 
df2.loc[df2['I']]

            A          B   C  D     E    F  G         H     I
sample 1  1.0 2013-01-02 NaN  3  test  foo  2  0.135307  True
sample 4  1.0 2013-01-02 NaN  3  test  foo -3  0.070618  True
sample 5  1.0 2013-01-02 NaN  3  test  foo  0  0.893761  True

In [310]:
# select all rows where E is equal to "test"
# or where G is positive
df2[(df2['E'] == "test") | (df2["G"] > 0)]

,A,B,C,D,E,F,G,H,phenotype,"(sample 4, C)"
sample 1,32.0,2013-01-02,NaN,5,test,foo,1,0.086815,NaN,3
sample 1,32.0,2013-01-02,NaN,3,unknown,foo,6,0.120409,NaN,3
sample 2,32.0,2013-01-02,NaN,3,train,foo,4,0.213125,NaN,3
sample 3,32.0,2013-01-02,NaN,3,train,foo,4,0.050358,NaN,3
sample 4,32.0,2013-01-02,3.0,3,test,foo,-2,0.072346,NaN,3
sample 5,10.0,2013-01-02,NaN,3,test,foo,4,0.798816,NaN,3

In [ ]:
# select all rows where E is equal to "test"
# or where G is positive
# equivalent to the above command; just a way to write expressions in shorthand
df2.query('(E == "test") | (G > 0)')

,A,B,C,D,E,F,G,H,phenotype,"(sample 4, C)"
sample 1,32.0,2013-01-02,NaN,5,test,foo,1,0.086815,NaN,3
sample 1,32.0,2013-01-02,NaN,3,unknown,foo,6,0.120409,NaN,3
sample 2,32.0,2013-01-02,NaN,3,train,foo,4,0.213125,NaN,3
sample 3,32.0,2013-01-02,NaN,3,train,foo,4,0.050358,NaN,3
sample 4,32.0,2013-01-02,3.0,3,test,foo,-2,0.072346,NaN,3
sample 5,10.0,2013-01-02,NaN,3,test,foo,4,0.798816,NaN,3

In [303]:
# select rows where column E contains either test or train as categories
df2[df2['E'].isin(["test", "train"])]

,A,B,C,D,E,F,G,H,phenotype,"(sample 4, C)"
sample 1,32.0,2013-01-02,NaN,5,test,foo,1,0.086815,NaN,3
sample 2,10.0,2013-01-02,NaN,3,train,foo,-5,0.731428,NaN,3
sample 2,32.0,2013-01-02,NaN,3,train,foo,4,0.213125,NaN,3
sample 3,32.0,2013-01-02,NaN,3,train,foo,4,0.050358,NaN,3
sample 4,32.0,2013-01-02,3.0,3,test,foo,-2,0.072346,NaN,3
sample 5,10.0,2013-01-02,NaN,3,test,foo,4,0.798816,NaN,3

In [304]:
# mask all values in the original data where the statement below is not True
# i.e show me full row entries where column A is less than 15, all other rows
# should be NaN/NaT/None depending on series dtype for the column
df2.where(df2['A'] < 15)

,A,B,C,D,E,F,G,H,phenotype,"(sample 4, C)"
sample 1,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sample 2,10.0,2013-01-02,NaN,3.0,train,foo,-5.0,0.731428,NaN,3.0
sample 1,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sample 2,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sample 3,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sample 4,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sample 5,10.0,2013-01-02,NaN,3.0,test,foo,4.0,0.798816,NaN,3.0

In [305]:
# inverse behavior of where
# i.e. show me full row values where this is false/not true - hence mask these rows
df2.mask(df2['A'] < 15)

,A,B,C,D,E,F,G,H,phenotype,"(sample 4, C)"
sample 1,32.0,2013-01-02,NaN,5.0,test,foo,1.0,0.086815,NaN,3.0
sample 2,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sample 1,32.0,2013-01-02,NaN,3.0,unknown,foo,6.0,0.120409,NaN,3.0
sample 2,32.0,2013-01-02,NaN,3.0,train,foo,4.0,0.213125,NaN,3.0
sample 3,32.0,2013-01-02,NaN,3.0,train,foo,4.0,0.050358,NaN,3.0
sample 4,32.0,2013-01-02,3.0,3.0,test,foo,-2.0,0.072346,NaN,3.0
sample 5,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Example: setting/updating

In [284]:
# make a new series
# Setting a new column automatically aligns the data by the indexes
# matches the index listed to the df index just like a merge by row name
pheno = pd.Series(["wt", "wt", "wt" ,"wt", "ko", "ko", "ko", "ko"],  [0, 2, 4, 6, 1, 3, 5, 7])
df2_nonamed_index["phenotype"] = pheno
df2_nonamed_index

     A          B    C  D      E    F phenotype
0  1.0 2013-01-02  1.0  3   test  foo        wt
1  1.0 2013-01-02  1.0  3  train  foo        ko
2  1.0 2013-01-02  1.0  3   test  foo        wt
3  1.0 2013-01-02  1.0  3  train  foo        ko
4  1.0 2013-01-02  1.0  3   test  foo        wt
5  1.0 2013-01-02  1.0  3  train  foo        ko
6  1.0 2013-01-02  1.0  3   test  foo        wt
7  1.0 2013-01-02  1.0  3  train  foo        ko

In [285]:
# change/set/update value of cell by label
df2.at["sample 4", "C"]  = 3
df2

,A,B,C,D,E,F,G,H,phenotype,"(sample 4, C)"
sample 1,16.0,2013-01-02,NaN,5,test,foo,1,0.086815,NaN,3
sample 2,10.0,2013-01-02,NaN,3,train,foo,-5,0.731428,NaN,3
sample 1,16.0,2013-01-02,NaN,3,unknown,foo,6,0.120409,NaN,3
sample 2,16.0,2013-01-02,NaN,3,train,foo,4,0.213125,NaN,3
sample 3,16.0,2013-01-02,NaN,3,train,foo,4,0.050358,NaN,3
sample 4,16.0,2013-01-02,3.0,3,test,foo,-2,0.072346,NaN,3
sample 5,10.0,2013-01-02,NaN,3,test,foo,4,0.798816,NaN,3

In [286]:
# change/set/update value of cell by position
# 1st row and 4th column (col index 3 b/c 0-indexed) set value to 5
df2.iat[0, 3]  = 5
df2

,A,B,C,D,E,F,G,H,phenotype,"(sample 4, C)"
sample 1,16.0,2013-01-02,NaN,5,test,foo,1,0.086815,NaN,3
sample 2,10.0,2013-01-02,NaN,3,train,foo,-5,0.731428,NaN,3
sample 1,16.0,2013-01-02,NaN,3,unknown,foo,6,0.120409,NaN,3
sample 2,16.0,2013-01-02,NaN,3,train,foo,4,0.213125,NaN,3
sample 3,16.0,2013-01-02,NaN,3,train,foo,4,0.050358,NaN,3
sample 4,16.0,2013-01-02,3.0,3,test,foo,-2,0.072346,NaN,3
sample 5,10.0,2013-01-02,NaN,3,test,foo,4,0.798816,NaN,3

In [287]:
# multiple each cell in column A for every row by 2 
# and overwrite the results
df2.loc[:,"A"] = df2.loc[:,"A"]*2
df2

,A,B,C,D,E,F,G,H,phenotype,"(sample 4, C)"
sample 1,32.0,2013-01-02,NaN,5,test,foo,1,0.086815,NaN,3
sample 2,20.0,2013-01-02,NaN,3,train,foo,-5,0.731428,NaN,3
sample 1,32.0,2013-01-02,NaN,3,unknown,foo,6,0.120409,NaN,3
sample 2,32.0,2013-01-02,NaN,3,train,foo,4,0.213125,NaN,3
sample 3,32.0,2013-01-02,NaN,3,train,foo,4,0.050358,NaN,3
sample 4,32.0,2013-01-02,3.0,3,test,foo,-2,0.072346,NaN,3
sample 5,20.0,2013-01-02,NaN,3,test,foo,4,0.798816,NaN,3

In [288]:
# of rows where column H is greater than 0.5, 
# set column A of those rows to 10
df2.loc[df2['H'] > 0.5, "A"] = 10

## Working with missing data