## Pandas Cookbook 
see: https://pandas.pydata.org/docs/user_guide/index.html

In [1]:
import numpy as np
import pandas as pd

## Generate new pandas objects
Two main data structures in pandas:  
* Series = 1-dimensional iteratable such as a list of integers, a dictionary of strings, an array of objects, etc...
* DataFrame - 2-dimensional that works like a table with rows and columns

### Series examples

In [2]:
# generate a series
int_series_data = pd.Series([1, 5, 5, np.nan, 6, 8])
int_series_data

0    1.0
1    5.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
# generate string series
str_series_data = pd.Series(["this", "is", "a", "string", "series", "it", "can", "contain", "duplicates", "duplicates", "count", "the", "dups", "duplicates"])
str_series_data

0           this
1             is
2              a
3         string
4         series
5             it
6            can
7        contain
8     duplicates
9     duplicates
10         count
11           the
12          dups
13    duplicates
dtype: str

In [4]:
# generate string series
# index equates to row names
str_series_data = pd.Series(["this", "is", "a", "string", "series", "it", "can", "contain", "duplicates", "duplicates", "count", "the", "dups", "duplicates"], 
                            index=["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n"])
str_series_data

a          this
b            is
c             a
d        string
e        series
f            it
g           can
h       contain
i    duplicates
j    duplicates
k         count
l           the
m          dups
n    duplicates
dtype: str

In [5]:
# generate string series
# index equates to row names - DO NOT NEED TO BE UNIQUE!
str_series_data = pd.Series(["this", "is", "a", "string", "series", "it", "can", "contain", "duplicates", "duplicates", "count", "the", "dups", "duplicates"], 
                            index=["a", "a", "a", "a", "e", "f", "g", "h", "c", "j", "k", "l", "b", "c"])
str_series_data

a          this
a            is
a             a
a        string
e        series
f            it
g           can
h       contain
c    duplicates
j    duplicates
k         count
l           the
b          dups
c    duplicates
dtype: str

### Dataframe example

In [6]:
# generate dataframes 
# date_range() produces a numpy array
dates_df = pd.date_range(start = "20130101", 
                         periods=6, 
                         freq="D",     
                         inclusive="both")
dates_df

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [7]:
# generate data frame by dictionary
df2_nonamed_index = pd.DataFrame(data= {
     "A": 1.0,
     "B": pd.Timestamp("20130102"),
     "C": pd.Series(1, index = range(8), dtype = "float32"),
     "D": np.array([3] * 8, dtype = "int32"),
     "E": pd.Categorical(values=["test", "train", "test", "train", "test", "train", "test", "train"]),
     "F": "foo"
     }
)
df2_nonamed_index

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo
4  1.0 2013-01-02  1.0  3   test  foo
5  1.0 2013-01-02  1.0  3  train  foo
6  1.0 2013-01-02  1.0  3   test  foo
7  1.0 2013-01-02  1.0  3  train  foo

In [8]:
# generate data frame by dictionary
# now add index (row names)
df2 = pd.DataFrame(data= {
     "A": 1.0,
     "B": pd.Timestamp("20130102"),
     "C": pd.Series(1, index = range(4), dtype = "float32"),
     "D": np.array([3] * 4, dtype = "int32"),
     "E": pd.Categorical(values=["test", "train", "test", "train"]),
     "F": "foo"
     },index=['sample {}'.format(num) for num in range(1,5)]
)
df2

            A          B   C  D      E    F
sample 1  1.0 2013-01-02 NaN  3   test  foo
sample 2  1.0 2013-01-02 NaN  3  train  foo
sample 3  1.0 2013-01-02 NaN  3   test  foo
sample 4  1.0 2013-01-02 NaN  3  train  foo

In [9]:
# generate data frame by dictionary
# now add index (row names) - DOES NOT NEED TO BE UNIQUE!!
df2 = pd.DataFrame(data= {
     "A": 1.0,
     "B": pd.Timestamp("20130102"),
     "C": pd.Series(1, index = range(7), dtype = "float32"),
     "D": np.array([3] * 7, dtype = "int32"),
     "E": pd.Categorical(values=["test", "train", "unknown", "train", "train", "test", "test"]),
     "F": "foo",
     "G": np.random.randint(low = -5, high = 7, size = 7),
     "H": np.random.ranf(size = 7),
     "I": [True, False, False, False, False, True, True],
     "J": [np.nan, None, None, np.nan, pd.NaT, pd.NA, None]
     },
     index=["sample 1", "sample 2", "sample 1", "sample 2", "sample 3", "sample 4", "sample 5"]
)
df2

            A          B   C  D        E    F  G         H      I     J
sample 1  1.0 2013-01-02 NaN  3     test  foo  2  0.168002   True   NaN
sample 2  1.0 2013-01-02 NaN  3    train  foo  6  0.836041  False  None
sample 1  1.0 2013-01-02 NaN  3  unknown  foo  6  0.725179  False  None
sample 2  1.0 2013-01-02 NaN  3    train  foo -2  0.972486  False   NaN
sample 3  1.0 2013-01-02 NaN  3    train  foo -5  0.981977  False   NaT
sample 4  1.0 2013-01-02 NaN  3     test  foo -5  0.685862   True  <NA>
sample 5  1.0 2013-01-02 NaN  3     test  foo  5  0.026497   True  None

In [10]:
# print column "A"
df2.A

sample 1    1.0
sample 2    1.0
sample 1    1.0
sample 2    1.0
sample 3    1.0
sample 4    1.0
sample 5    1.0
Name: A, dtype: float64

In [11]:
# axis = 0 (rows), axis = 1 (columns)
# count the number of non-NaN entries in each row
# in pandas, NaN, NaT, None, pandas.NA are all considered as NA
df2.count(axis = 0) 

# the results below would indicate that for column "C" all rows(index in our case samples) are all NaN/NA/NaT/None and that column "A", has 7 rows(samples in our case) values that are not NA

A    7
B    7
C    0
D    7
E    7
F    7
G    7
H    7
I    7
J    0
dtype: int64

In [14]:
# axis = 0 (rows), axis = 1 (columns)
# count the number of non-NaN, non-NaT, non-None, non-NA entries in each column
# in pandas, NaN, NaT, None, pandas.NA are all considered as NA
df2.count(axis = 1, numeric_only = False)

# the results below would indicate that 8 columns in the first occurence of "sample 1" row/index (sample in our case) all contain values that are not NA
# as a matter of fact, all samples (rows) have 8 columns that don't contain NA.  This is true because we have10 columns, and we know column "C" and "J" is NA for all rows

sample 1    8
sample 2    8
sample 1    8
sample 2    8
sample 3    8
sample 4    8
sample 5    8
dtype: int64

## Viewing contents in pandas objects
* `.head()`
* `.tail()`
* `.index`
* `.to_numpy()`
* `.dtypes`
* `.describe()`
* `.T`
* `.sort_index()`
* `.sort_values()`

In [15]:
# view first 10 rows/indices
df2.head(3)

            A          B   C  D        E    F  G         H      I     J
sample 1  1.0 2013-01-02 NaN  3     test  foo  2  0.168002   True   NaN
sample 2  1.0 2013-01-02 NaN  3    train  foo  6  0.836041  False  None
sample 1  1.0 2013-01-02 NaN  3  unknown  foo  6  0.725179  False  None

In [16]:
# view the last row/index
df2.tail(1)

            A          B   C  D     E    F  G         H     I     J
sample 5  1.0 2013-01-02 NaN  3  test  foo  5  0.026497  True  None

In [17]:
# show the row names of the data frame (indices/index)
df2.index

Index(['sample 1', 'sample 2', 'sample 1', 'sample 2', 'sample 3', 'sample 4',
       'sample 5'],
      dtype='str')

In [18]:
# view data frame as a numpy array with rows(indices) and columns stripped off
# the dtype is inferred from the pandas dataframe.  However, since pandas allows each column to have a dtype, numpy can only handle
# a single dtype for the whole array, so numpy automatically infers the dtype based on the minimum type that can cover all types in the
# dataframe
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), nan, 3, 'test', 'foo', 2,
        0.16800226995646272, True, nan],
       [1.0, Timestamp('2013-01-02 00:00:00'), nan, 3, 'train', 'foo', 6,
        0.8360408713109169, False, None],
       [1.0, Timestamp('2013-01-02 00:00:00'), nan, 3, 'unknown', 'foo',
        6, 0.7251790847842924, False, None],
       [1.0, Timestamp('2013-01-02 00:00:00'), nan, 3, 'train', 'foo',
        -2, 0.9724857902108198, False, nan],
       [1.0, Timestamp('2013-01-02 00:00:00'), nan, 3, 'train', 'foo',
        -5, 0.9819766904220946, False, NaT],
       [1.0, Timestamp('2013-01-02 00:00:00'), nan, 3, 'test', 'foo', -5,
        0.6858624223570924, True, <NA>],
       [1.0, Timestamp('2013-01-02 00:00:00'), nan, 3, 'test', 'foo', 5,
        0.026497155910599313, True, None]], dtype=object)

In [19]:
# view the type for each column in the data frame
df2.dtypes

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
G             int64
H           float64
I              bool
J            object
dtype: object

In [20]:
# calculate and quickly view the summary statistics for a particular column in the data frame
df2.A.describe()

count    7.0
mean     1.0
std      0.0
min      1.0
25%      1.0
50%      1.0
75%      1.0
max      1.0
Name: A, dtype: float64

In [21]:
# calculate and quickly view the summary statistics for a particular column in the data frame
df2.G.describe()

count    7.000000
mean     1.000000
std      4.966555
min     -5.000000
25%     -3.500000
50%      2.000000
75%      5.500000
max      6.000000
Name: G, dtype: float64

In [22]:
# view the dataframe after transposing the dataframe; columns become indices (rows) and rows (indices) become columns
df2.T

,sample 1,sample 2,sample 1,sample 2,sample 3,sample 4,sample 5
A,1.0,1.0,1.0,1.0,1.0,1.0,1.0
B,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00
C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
D,3,3,3,3,3,3,3
E,test,train,unknown,train,train,test,test
F,foo,foo,foo,foo,foo,foo,foo
G,2,6,6,-2,-5,-5,5
H,0.168002,0.836041,0.725179,0.972486,0.981977,0.685862,0.026497
I,True,False,False,False,False,True,True
J,NaN,None,None,NaN,NaT,<NA>,None

In [24]:
# view the dataframe after it is sorted
# sort by rows (axis=0)
# which row index do you want to sort by; default is 0/None, however, if you have mutliple indices levels, you can choose which one to base the sort on
df2.sort_index(axis=0, level = 0, ascending= True, kind = 'quicksort', inplace=False)

            A          B   C  D        E    F  G         H      I     J
sample 1  1.0 2013-01-02 NaN  3     test  foo  2  0.168002   True   NaN
sample 1  1.0 2013-01-02 NaN  3  unknown  foo  6  0.725179  False  None
sample 2  1.0 2013-01-02 NaN  3    train  foo  6  0.836041  False  None
sample 2  1.0 2013-01-02 NaN  3    train  foo -2  0.972486  False   NaN
sample 3  1.0 2013-01-02 NaN  3    train  foo -5  0.981977  False   NaT
sample 4  1.0 2013-01-02 NaN  3     test  foo -5  0.685862   True  <NA>
sample 5  1.0 2013-01-02 NaN  3     test  foo  5  0.026497   True  None

In [25]:
# sorts row (indices) by column G in descending order
df2.sort_values(by = "G", ascending=False)

            A          B   C  D        E    F  G         H      I     J
sample 2  1.0 2013-01-02 NaN  3    train  foo  6  0.836041  False  None
sample 1  1.0 2013-01-02 NaN  3  unknown  foo  6  0.725179  False  None
sample 5  1.0 2013-01-02 NaN  3     test  foo  5  0.026497   True  None
sample 1  1.0 2013-01-02 NaN  3     test  foo  2  0.168002   True   NaN
sample 2  1.0 2013-01-02 NaN  3    train  foo -2  0.972486  False   NaN
sample 3  1.0 2013-01-02 NaN  3    train  foo -5  0.981977  False   NaT
sample 4  1.0 2013-01-02 NaN  3     test  foo -5  0.685862   True  <NA>

In [27]:
# sorts row (indices) by column G in descending order
# can sort by multiple columns
# doesn't change because column D is all the same values but it would perform a second sort on col D
df2.sort_values(by = ["G", "D"], ascending=False)

            A          B   C  D        E    F  G         H      I     J
sample 2  1.0 2013-01-02 NaN  3    train  foo  6  0.836041  False  None
sample 1  1.0 2013-01-02 NaN  3  unknown  foo  6  0.725179  False  None
sample 5  1.0 2013-01-02 NaN  3     test  foo  5  0.026497   True  None
sample 1  1.0 2013-01-02 NaN  3     test  foo  2  0.168002   True   NaN
sample 2  1.0 2013-01-02 NaN  3    train  foo -2  0.972486  False   NaN
sample 3  1.0 2013-01-02 NaN  3    train  foo -5  0.981977  False   NaT
sample 4  1.0 2013-01-02 NaN  3     test  foo -5  0.685862   True  <NA>

## Selecting and Subsetting Data  
* Getitem (`[]`) - good for rearranging order of columns in a dataframe
* slicing (`:`) - good for selecting rows/indices
* by label (`.loc[]` or `.at[]`)
* by position (`.iloc[]` or `.iat[]`)
* boolean indexing (`>`, `<`, `>=`, `<=`, `==`, `&`, `|`, `.isin()`, `.query()`)
* keep original shape but show where (`.where()`) or mask values (`.mask()`)
* setting/updating

### Example: Getitem (`[]`) - good for rearranging order of columns in a dataframe

In [28]:
# This will return a series for what is listed in column E
# df2["E"] and df2.E are equivalent, the main difference is the .E version can only be used if your columns only contain letter, numbers and underscores
# if you have spaces or special characters then the GetItem (["E"]) approach as shown below must be used
df2["E"]

sample 1       test
sample 2      train
sample 1    unknown
sample 2      train
sample 3      train
sample 4       test
sample 5       test
Name: E, dtype: category
Categories (3, str): ['test', 'train', 'unknown']

In [29]:
# select columns G, A, and B and rearrange them in the same order provided
df2[["G", "A", "B"]]

          G    A          B
sample 1  2  1.0 2013-01-02
sample 2  6  1.0 2013-01-02
sample 1  6  1.0 2013-01-02
sample 2 -2  1.0 2013-01-02
sample 3 -5  1.0 2013-01-02
sample 4 -5  1.0 2013-01-02
sample 5  5  1.0 2013-01-02

### Example: slicing (`:`) - good for selecting rows/indices

In [30]:
# select the first two rows of the data frame
# note, the last number is non-inclusive and as with python, dataframes are 0-indexed
df2[0:2]

            A          B   C  D      E    F  G         H      I     J
sample 1  1.0 2013-01-02 NaN  3   test  foo  2  0.168002   True   NaN
sample 2  1.0 2013-01-02 NaN  3  train  foo  6  0.836041  False  None

In [31]:
# select the last 3 rows
df2[df2.shape[0]-3:df2.shape[0]]

            A          B   C  D      E    F  G         H      I     J
sample 3  1.0 2013-01-02 NaN  3  train  foo -5  0.981977  False   NaT
sample 4  1.0 2013-01-02 NaN  3   test  foo -5  0.685862   True  <NA>
sample 5  1.0 2013-01-02 NaN  3   test  foo  5  0.026497   True  None

### Example: by label (`.loc[]` or `.at[]`)

In [32]:
# subset to all rows of columns E and G only
df2.loc[:, ["E", "G"]]

                E  G
sample 1     test  2
sample 2    train  6
sample 1  unknown  6
sample 2    train -2
sample 3    train -5
sample 4     test -5
sample 5     test  5

In [34]:
# subset to rows called "sample 1" and of columns E and G only
df2.loc["sample 1", ["E", "G"]]

                E  G
sample 1     test  2
sample 1  unknown  6

In [35]:
# subset to rows called "sample 1" and "sample 2" and of columns E and G only
df2.loc[["sample 1", "sample 2"], ["E", "G"]]

                E  G
sample 1     test  2
sample 1  unknown  6
sample 2    train  6
sample 2    train -2

In [36]:
# For getting fast access to a scalar (equivalent to the prior method)
# but for single scalar values this is fastest
df2.at["sample 5", "G"]

np.int64(5)

### Example: by position (`.iloc[]` or `.iat[]`)

In [37]:
# select first 2 rows and 4th row, but keep all columns
df2.iloc[[0,1,3],:]

            A          B   C  D      E    F  G         H      I     J
sample 1  1.0 2013-01-02 NaN  3   test  foo  2  0.168002   True   NaN
sample 2  1.0 2013-01-02 NaN  3  train  foo  6  0.836041  False  None
sample 2  1.0 2013-01-02 NaN  3  train  foo -2  0.972486  False   NaN

In [38]:
# keep all rows but select first 3 columns
df2.iloc[:,0:3]

            A          B   C
sample 1  1.0 2013-01-02 NaN
sample 2  1.0 2013-01-02 NaN
sample 1  1.0 2013-01-02 NaN
sample 2  1.0 2013-01-02 NaN
sample 3  1.0 2013-01-02 NaN
sample 4  1.0 2013-01-02 NaN
sample 5  1.0 2013-01-02 NaN

In [39]:
# get value of cell at index 1 (2nd row) and column index 7 (8th column)
df2.iloc[1,7]

np.float64(0.8360408713109169)

In [40]:
# get value of cell at index 1 (2nd row) and column index 7 (8th column)
# faster access for singular scalar value
df2.iat[1,7]

np.float64(0.8360408713109169)

### boolean indexing (`>`, `<`, `>=`, `<=`, `==`, `&`, `|`, `.isin()`, `.query()`)

In [41]:
# select all rows where G is negative
df2[df2['G'] < 0]

            A          B   C  D      E    F  G         H      I     J
sample 2  1.0 2013-01-02 NaN  3  train  foo -2  0.972486  False   NaN
sample 3  1.0 2013-01-02 NaN  3  train  foo -5  0.981977  False   NaT
sample 4  1.0 2013-01-02 NaN  3   test  foo -5  0.685862   True  <NA>

In [42]:
# select all rows where G is negative and H is greater than or equal to 0.50
df2[(df2['G'] < 0) & (df2['H'] >= 0.50)]

            A          B   C  D      E    F  G         H      I     J
sample 2  1.0 2013-01-02 NaN  3  train  foo -2  0.972486  False   NaN
sample 3  1.0 2013-01-02 NaN  3  train  foo -5  0.981977  False   NaT
sample 4  1.0 2013-01-02 NaN  3   test  foo -5  0.685862   True  <NA>

In [43]:
# select all rows where E is equal to "train"
df2[(df2['E'] == "train")]

            A          B   C  D      E    F  G         H      I     J
sample 2  1.0 2013-01-02 NaN  3  train  foo  6  0.836041  False  None
sample 2  1.0 2013-01-02 NaN  3  train  foo -2  0.972486  False   NaN
sample 3  1.0 2013-01-02 NaN  3  train  foo -5  0.981977  False   NaT

In [44]:
# select all rows where E is not equal to "train"
df2[(df2['E'] != "train")]

            A          B   C  D        E    F  G         H      I     J
sample 1  1.0 2013-01-02 NaN  3     test  foo  2  0.168002   True   NaN
sample 1  1.0 2013-01-02 NaN  3  unknown  foo  6  0.725179  False  None
sample 4  1.0 2013-01-02 NaN  3     test  foo -5  0.685862   True  <NA>
sample 5  1.0 2013-01-02 NaN  3     test  foo  5  0.026497   True  None

In [45]:
# select all rows where I is False (~ negates the default of True )
df2.loc[~df2['I']]

            A          B   C  D        E    F  G         H      I     J
sample 2  1.0 2013-01-02 NaN  3    train  foo  6  0.836041  False  None
sample 1  1.0 2013-01-02 NaN  3  unknown  foo  6  0.725179  False  None
sample 2  1.0 2013-01-02 NaN  3    train  foo -2  0.972486  False   NaN
sample 3  1.0 2013-01-02 NaN  3    train  foo -5  0.981977  False   NaT

In [46]:
# select all rows where I is True 
df2.loc[df2['I']]

            A          B   C  D     E    F  G         H     I     J
sample 1  1.0 2013-01-02 NaN  3  test  foo  2  0.168002  True   NaN
sample 4  1.0 2013-01-02 NaN  3  test  foo -5  0.685862  True  <NA>
sample 5  1.0 2013-01-02 NaN  3  test  foo  5  0.026497  True  None

In [47]:
# select all rows where E is equal to "test"
# or where G is positive
df2[(df2['E'] == "test") | (df2["G"] > 0)]

            A          B   C  D        E    F  G         H      I     J
sample 1  1.0 2013-01-02 NaN  3     test  foo  2  0.168002   True   NaN
sample 2  1.0 2013-01-02 NaN  3    train  foo  6  0.836041  False  None
sample 1  1.0 2013-01-02 NaN  3  unknown  foo  6  0.725179  False  None
sample 4  1.0 2013-01-02 NaN  3     test  foo -5  0.685862   True  <NA>
sample 5  1.0 2013-01-02 NaN  3     test  foo  5  0.026497   True  None

In [48]:
# select all rows where E is equal to "test"
# or where G is positive
# equivalent to the above command; just a way to write expressions in shorthand
# DataFrame.query() using numexpr is slightly faster than Python for large frames.
# You will only see the performance benefits of using the numexpr engine with 
# DataFrame.query() if your frame has more than approximately 100,000 rows.


df2.query('(E == "test") | (G > 0)')

            A          B   C  D        E    F  G         H      I     J
sample 1  1.0 2013-01-02 NaN  3     test  foo  2  0.168002   True   NaN
sample 2  1.0 2013-01-02 NaN  3    train  foo  6  0.836041  False  None
sample 1  1.0 2013-01-02 NaN  3  unknown  foo  6  0.725179  False  None
sample 4  1.0 2013-01-02 NaN  3     test  foo -5  0.685862   True  <NA>
sample 5  1.0 2013-01-02 NaN  3     test  foo  5  0.026497   True  None

In [49]:
# select rows where column E contains either test or train as categories
df2[df2['E'].isin(["test", "train"])]

            A          B   C  D      E    F  G         H      I     J
sample 1  1.0 2013-01-02 NaN  3   test  foo  2  0.168002   True   NaN
sample 2  1.0 2013-01-02 NaN  3  train  foo  6  0.836041  False  None
sample 2  1.0 2013-01-02 NaN  3  train  foo -2  0.972486  False   NaN
sample 3  1.0 2013-01-02 NaN  3  train  foo -5  0.981977  False   NaT
sample 4  1.0 2013-01-02 NaN  3   test  foo -5  0.685862   True  <NA>
sample 5  1.0 2013-01-02 NaN  3   test  foo  5  0.026497   True  None

In [50]:
# mask all values in the original data where the statement below is not True
# i.e show me full row entries where column A is less than 15, all other rows
# should be NaN/NaT/None depending on series dtype for the column
df2.where(df2['A'] < 15)

            A          B   C  D        E    F  G         H      I     J
sample 1  1.0 2013-01-02 NaN  3     test  foo  2  0.168002   True   NaN
sample 2  1.0 2013-01-02 NaN  3    train  foo  6  0.836041  False  None
sample 1  1.0 2013-01-02 NaN  3  unknown  foo  6  0.725179  False  None
sample 2  1.0 2013-01-02 NaN  3    train  foo -2  0.972486  False   NaN
sample 3  1.0 2013-01-02 NaN  3    train  foo -5  0.981977  False   NaT
sample 4  1.0 2013-01-02 NaN  3     test  foo -5  0.685862   True  <NA>
sample 5  1.0 2013-01-02 NaN  3     test  foo  5  0.026497   True  None

In [51]:
# inverse behavior of where
# i.e. show me full row values where this is false/not true - hence mask these rows
df2.mask(df2['A'] < 15)

           A   B   C   D    E    F   G   H    I    J
sample 1 NaN NaT NaN NaN  NaN  NaN NaN NaN  NaN  NaN
sample 2 NaN NaT NaN NaN  NaN  NaN NaN NaN  NaN  NaN
sample 1 NaN NaT NaN NaN  NaN  NaN NaN NaN  NaN  NaN
sample 2 NaN NaT NaN NaN  NaN  NaN NaN NaN  NaN  NaN
sample 3 NaN NaT NaN NaN  NaN  NaN NaN NaN  NaN  NaN
sample 4 NaN NaT NaN NaN  NaN  NaN NaN NaN  NaN  NaN
sample 5 NaN NaT NaN NaN  NaN  NaN NaN NaN  NaN  NaN

### Example: setting/updating

In [53]:
# make a new series
# Setting a new column automatically aligns the data by the indexes
# matches the index listed to the df index just like a merge by row name
pheno = pd.Series(["wt", "wt", "wt" ,"wt", "ko", "ko", "ko", "ko"],  [0, 2, 4, 6, 1, 3, 5, 7])
df2_nonamed_index["phenotype"] = pheno
df2_nonamed_index

     A          B    C  D      E    F phenotype
0  1.0 2013-01-02  1.0  3   test  foo        wt
1  1.0 2013-01-02  1.0  3  train  foo        ko
2  1.0 2013-01-02  1.0  3   test  foo        wt
3  1.0 2013-01-02  1.0  3  train  foo        ko
4  1.0 2013-01-02  1.0  3   test  foo        wt
5  1.0 2013-01-02  1.0  3  train  foo        ko
6  1.0 2013-01-02  1.0  3   test  foo        wt
7  1.0 2013-01-02  1.0  3  train  foo        ko

In [54]:
# change/set/update value of cell by label
df2.at["sample 4", "C"]  = 3
df2

            A          B    C  D        E    F  G         H      I     J
sample 1  1.0 2013-01-02  NaN  3     test  foo  2  0.168002   True   NaN
sample 2  1.0 2013-01-02  NaN  3    train  foo  6  0.836041  False  None
sample 1  1.0 2013-01-02  NaN  3  unknown  foo  6  0.725179  False  None
sample 2  1.0 2013-01-02  NaN  3    train  foo -2  0.972486  False   NaN
sample 3  1.0 2013-01-02  NaN  3    train  foo -5  0.981977  False   NaT
sample 4  1.0 2013-01-02  3.0  3     test  foo -5  0.685862   True  <NA>
sample 5  1.0 2013-01-02  NaN  3     test  foo  5  0.026497   True  None

In [55]:
# change/set/update value of cell by position
# 1st row and 4th column (col index 3 b/c 0-indexed) set value to 5
df2.iat[0, 3]  = 5
df2

            A          B    C  D        E    F  G         H      I     J
sample 1  1.0 2013-01-02  NaN  5     test  foo  2  0.168002   True   NaN
sample 2  1.0 2013-01-02  NaN  3    train  foo  6  0.836041  False  None
sample 1  1.0 2013-01-02  NaN  3  unknown  foo  6  0.725179  False  None
sample 2  1.0 2013-01-02  NaN  3    train  foo -2  0.972486  False   NaN
sample 3  1.0 2013-01-02  NaN  3    train  foo -5  0.981977  False   NaT
sample 4  1.0 2013-01-02  3.0  3     test  foo -5  0.685862   True  <NA>
sample 5  1.0 2013-01-02  NaN  3     test  foo  5  0.026497   True  None

In [56]:
# multiple each cell in column A for every row by 2 
# and overwrite the results
df2.loc[:,"A"] = df2.loc[:,"A"]*2
df2

            A          B    C  D        E    F  G         H      I     J
sample 1  2.0 2013-01-02  NaN  5     test  foo  2  0.168002   True   NaN
sample 2  2.0 2013-01-02  NaN  3    train  foo  6  0.836041  False  None
sample 1  2.0 2013-01-02  NaN  3  unknown  foo  6  0.725179  False  None
sample 2  2.0 2013-01-02  NaN  3    train  foo -2  0.972486  False   NaN
sample 3  2.0 2013-01-02  NaN  3    train  foo -5  0.981977  False   NaT
sample 4  2.0 2013-01-02  3.0  3     test  foo -5  0.685862   True  <NA>
sample 5  2.0 2013-01-02  NaN  3     test  foo  5  0.026497   True  None

In [57]:
# of rows where column H is greater than 0.5, 
# set column A of those rows to 10
df2.loc[df2['H'] > 0.5, "A"] = 10

## Working with missing data  

`pandas` considers data "missing" or NA and those values are not considered when applying computational calculations.  `pandas` considers the following missing or NA:  
* `numpy.nan`  
* `numpy.NaT` (for time)  
* `None`  
* `<NA>`

To detect "missing" data of these types, the following commands can be applied to a pandas dataframe and pandas will treat them as NA values or missing:  
* `.isna()`  
* `.notna()`  

Boolean comparisons, however, do not equate them to NA, despite the two commands above treating them as NA.  

The following commands can also be used to drop rows or columns that are only NA or to create columns and row and placehold and NA in the cells:  
* `.dropna()`  
* `.fillna()` 
* `.ffill()` and `.bfill()` fill in NAs either from forward or backward propogation

To fill NAs by more complex interpolation methods, visit: https://pandas.pydata.org/docs/user_guide/missing_data.html#interpolation

### Example: detect NAs with `.isna()` and `.notna()`

In [67]:
# in a series check for NA
pd.isna(int_series_data)

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

In [84]:
# position in a series check for NA
int_series_data[1] is pd.NA

False

In [69]:
# position in a series check for NA
# WARNING: This is false, because this is np.na, not pd.NA, but 
# still considered NA when pandas performs calculations or isna() or notna() is used
int_series_data[3] is pd.NA

False

In [85]:
# data frame chechking for NA
df2.J.isna()

sample 1    True
sample 2    True
sample 1    True
sample 2    True
sample 3    True
sample 4    True
sample 5    True
Name: J, dtype: bool

In [71]:
# data frame chechking if values anything except NA
df2.J.notna()

sample 1    False
sample 2    False
sample 1    False
sample 2    False
sample 3    False
sample 4    False
sample 5    False
Name: J, dtype: bool

### Example: dropping rows and columns with NAs using `.dropna()`

In [82]:
# drop all rows that contain an NA
df2.dropna(axis = 0)

Empty DataFrame
Columns: [A, B, C, D, E, F, G, H, I, J]
Index: []

In [83]:
# drop all columns that contain an NA
df2.dropna(axis = 1)

             A          B  D        E    F  G         H      I
sample 1   2.0 2013-01-02  5     test  foo  2  0.168002   True
sample 2  10.0 2013-01-02  3    train  foo  6  0.836041  False
sample 1  10.0 2013-01-02  3  unknown  foo  6  0.725179  False
sample 2  10.0 2013-01-02  3    train  foo -2  0.972486  False
sample 3  10.0 2013-01-02  3    train  foo -5  0.981977  False
sample 4  10.0 2013-01-02  3     test  foo -5  0.685862   True
sample 5   2.0 2013-01-02  3     test  foo  5  0.026497   True

### Example: filling in NAs with `.fillna()`, `.ffill()`, and `.bfill()`

In [ ]:
# fill all NA values with the value 10 in column C
df2['C'].fillna(10.0)

sample 1    10.0
sample 2    10.0
sample 1    10.0
sample 2    10.0
sample 3    10.0
sample 4     3.0
sample 5    10.0
Name: C, dtype: float32

In [79]:
# You can also fill missing values based on mathematical operations
# In this case, take the mean of column C (remember NAs are not counted as values toward mathematical
# operations such as mean) and then anywhere there is an NA in column C replace with the mean of column
# C  
df2['C'].fillna(df2['C'].mean())

sample 1    3.0
sample 2    3.0
sample 1    3.0
sample 2    3.0
sample 3    3.0
sample 4    3.0
sample 5    3.0
Name: C, dtype: float32

In [ ]:
# You can also fill missing values based on mathematical operations
# In this case, take the mean of column H (remember NAs are not counted as values toward mathematical
# operations such as mean) and then anywhere there is an NA in column C replace with the mean of column
# H  
df2['C'].fillna(df2['H'].mean())

sample 1    0.628006
sample 2    0.628006
sample 1    0.628006
sample 2    0.628006
sample 3    0.628006
sample 4    3.000000
sample 5    0.628006
Name: C, dtype: float64

In [ ]:
# Find the first value what is not NA, and then take that value and fill all values that are NA after 
# that with the value, in this case the first case of a non-NA is sample 4 with the value of 3.0, so all
# other NAs after that should take on the value of 3.0 in column C
df2['C'].ffill()

sample 1    NaN
sample 2    NaN
sample 1    NaN
sample 2    NaN
sample 3    NaN
sample 4    3.0
sample 5    3.0
Name: C, dtype: float32

In [ ]:
# same as above but find the first occurence of non-NA starting at the bottom of column C.  When
# found take that value and replace all values that are NA with the value to the top.
df2['C'].bfill()

sample 1    3.0
sample 2    3.0
sample 1    3.0
sample 2    3.0
sample 3    3.0
sample 4    3.0
sample 5    NaN
Name: C, dtype: float32

## Merge, join, concatenate, and compare
Full docs here: https://pandas.pydata.org/docs/user_guide/merging.html#merge-join-concatenate-and-compare

* `pandas.concat()` - merge mutiple series or dataframes along a common index or column
  * WARNING - makes full copies of data unnecessarily so group all series, dfs together before calling `concat()`
* `.join()` - merge dataframes along columns
* `.merge()` - merge 2 dataframes or series similar to SQL joins
* `.compare()` - show differences between 2 series or dataframes

### Example: `concat()` vertical or horizontal concatenation of multiple dataframes or objects with either same set of indices or same column names

In [118]:
df2_nonamed_index

     A          B    C  D      E    F phenotype
0  1.0 2013-01-02  1.0  3   test  foo        wt
1  1.0 2013-01-02  1.0  3  train  foo        ko
2  1.0 2013-01-02  1.0  3   test  foo        wt
3  1.0 2013-01-02  1.0  3  train  foo        ko
4  1.0 2013-01-02  1.0  3   test  foo        wt
5  1.0 2013-01-02  1.0  3  train  foo        ko
6  1.0 2013-01-02  1.0  3   test  foo        wt
7  1.0 2013-01-02  1.0  3  train  foo        ko

In [119]:
df_new_obervations = pd.DataFrame(data = {
     "A": [2.0, 3.7],
     "B": pd.Timestamp("20260514"),
     "C": [np.nan, np.nan],
     "D": 3,
     "E": "test",
     "F": "bar",
     "phenotype": ["wt", "Wt"]}, 
     index=[8,9])

df_new_obervations

     A          B   C  D     E    F phenotype
8  2.0 2026-05-14 NaN  3  test  bar        wt
9  3.7 2026-05-14 NaN  3  test  bar        Wt

In [120]:
df_new_obervations_2 = pd.DataFrame(data = {
     "A": [4.8, 1.8],
     "B": pd.Timestamp("20260514"),
     "C": [np.nan, 1.0],
     "D": 3,
     "E": "train",
     "F": "bar",
     "phenotype": ["ko", "ko"]}, 
     index=[20,21])

df_new_obervations_2

      A          B    C  D      E    F phenotype
20  4.8 2026-05-14  NaN  3  train  bar        ko
21  1.8 2026-05-14  1.0  3  train  bar        ko

In [121]:
# vertical concatenation (append new sample to df in same order as all_dfs list)
# concatenate dfs in one concat call
all_dfs = [df2_nonamed_index, df_new_obervations, df_new_obervations_2]
veritcal_concat_df = pd.concat(objs=all_dfs, axis = 0, ignore_index= False)
veritcal_concat_df

      A          B    C  D      E    F phenotype
0   1.0 2013-01-02  1.0  3   test  foo        wt
1   1.0 2013-01-02  1.0  3  train  foo        ko
2   1.0 2013-01-02  1.0  3   test  foo        wt
3   1.0 2013-01-02  1.0  3  train  foo        ko
4   1.0 2013-01-02  1.0  3   test  foo        wt
5   1.0 2013-01-02  1.0  3  train  foo        ko
6   1.0 2013-01-02  1.0  3   test  foo        wt
7   1.0 2013-01-02  1.0  3  train  foo        ko
8   2.0 2026-05-14  NaN  3   test  bar        wt
9   3.7 2026-05-14  NaN  3   test  bar        Wt
20  4.8 2026-05-14  NaN  3  train  bar        ko
21  1.8 2026-05-14  1.0  3  train  bar        ko

In [122]:
# add new columns to existing samples
df2_nonamed_index

     A          B    C  D      E    F phenotype
0  1.0 2013-01-02  1.0  3   test  foo        wt
1  1.0 2013-01-02  1.0  3  train  foo        ko
2  1.0 2013-01-02  1.0  3   test  foo        wt
3  1.0 2013-01-02  1.0  3  train  foo        ko
4  1.0 2013-01-02  1.0  3   test  foo        wt
5  1.0 2013-01-02  1.0  3  train  foo        ko
6  1.0 2013-01-02  1.0  3   test  foo        wt
7  1.0 2013-01-02  1.0  3  train  foo        ko

In [123]:
df_new_obervations_2 = pd.DataFrame(data={
     "status": ["low", "med", "low", "high", "high", "low", "high", "med"],
     "temp": pd.Series(data = np.random.randint(low = 20, high = 100, size = 8))},
     index = [i for i in range(0,8)]
     )

df_new_obervations_2

  status  temp
0    low    54
1    med    70
2    low    70
3   high    41
4   high    58
5    low    48
6   high    46
7    med    39

In [124]:
# horizontal observations - add additional columns to existing indices
all_dfs = [df2_nonamed_index, df_new_obervations_2]
horizontal_concat_df = pd.concat(objs=all_dfs, axis=1, ignore_index= False)
horizontal_concat_df

     A          B    C  D      E    F phenotype status  temp
0  1.0 2013-01-02  1.0  3   test  foo        wt    low    54
1  1.0 2013-01-02  1.0  3  train  foo        ko    med    70
2  1.0 2013-01-02  1.0  3   test  foo        wt    low    70
3  1.0 2013-01-02  1.0  3  train  foo        ko   high    41
4  1.0 2013-01-02  1.0  3   test  foo        wt   high    58
5  1.0 2013-01-02  1.0  3  train  foo        ko    low    48
6  1.0 2013-01-02  1.0  3   test  foo        wt   high    46
7  1.0 2013-01-02  1.0  3  train  foo        ko    med    39

### Example: `.join()`  combining columns of different indexed dfs into a single combined df

In [128]:
left_df = pd.DataFrame(
     {"A": ["A0", "A1", "A2"],
      "B": ["B0", "B1", "B2"]},

      index = ["idxKey0", "idxKey1", "idxKey2"]
)

left_df

          A   B
idxKey0  A0  B0
idxKey1  A1  B1
idxKey2  A2  B2

In [ ]:
# this dataframe whs 2 index keys shared with left_df: idxKey0, idxKey2, but it is 
# also missing idxKey1 that is present in left_df and has a new key idxKey3 that is not present
# in left_df
right_df = pd.DataFrame(
     {"C": ["C0", "C2", "C3"],
      "D": ["D0", "D2", "D3"]},
      index=["idxKey0", "idxKey2", "idxKey3"]
)

right_df

          C   D
idxKey0  C0  D0
idxKey2  C2  D2
idxKey3  C3  D3

In [ ]:
# left joined
left_joined_df = left_df.join(right_df, how="left")
left_joined_df

          A   B    C    D
idxKey0  A0  B0   C0   D0
idxKey1  A1  B1  NaN  NaN
idxKey2  A2  B2   C2   D2

In [132]:
# right joined
right_joined_df = left_df.join(right_df, how="right")
right_joined_df

           A    B   C   D
idxKey0   A0   B0  C0  D0
idxKey2   A2   B2  C2  D2
idxKey3  NaN  NaN  C3  D3

In [133]:
# inner joined
inner_joined_df = left_df.join(right_df, how="inner")
inner_joined_df

          A   B   C   D
idxKey0  A0  B0  C0  D0
idxKey2  A2  B2  C2  D2

In [ ]:
# union of all keys
outer_joined_df = left_df.join(right_df,how = "outer")
outer_joined_df

           A    B    C    D
idxKey0   A0   B0   C0   D0
idxKey1   A1   B1  NaN  NaN
idxKey2   A2   B2   C2   D2
idxKey3  NaN  NaN   C3   D3

### Example: `.join()`  when dfs are multi-indexed

In [135]:
left_df = pd.DataFrame(
     {"A": ["A0", "A1", "A2"],
      "B": ["B0", "B1", "B2"]},
      index = pd.Index(["idxKey0", "idxKey1", "idxKey2"], name = "first_index")
)
left_df

              A   B
first_index
idxKey0      A0  B0
idxKey1      A1  B1
idxKey2      A2  B2

In [ ]:
# generating a set of multindices
index_for_right_df = pd.MultiIndex.from_tuples(
     [("idxKey0", "newK0"), ("idxKey1", "newK1"), ("idxKey2", "newK2"), ("idxKey3", "newK3")],
     names = ["first_index", "sec_index"]
)
index_for_right_df

MultiIndex([('idxKey0', 'newK0'),
            ('idxKey1', 'newK1'),
            ('idxKey2', 'newK2'),
            ('idxKey3', 'newK3')],
           names=['first_index', 'sec_index'])

In [ ]:
# make a multi-index df
right_df = pd.DataFrame({
     "C": ["C0", "C1", "C2", "C3"],
     "D": ["D0", "D1", "D2", "D3"]},
     index = index_for_right_df
)

right_df

                        C   D
first_index sec_index
idxKey0     newK0      C0  D0
idxKey1     newK1      C1  D1
idxKey2     newK2      C2  D2
idxKey3     newK3      C3  D3

In [ ]:
# join 2 multi-index dfs with inner join
multiindex_inner_df = left_df.join(right_df, how = "inner")
multiindex_inner_df

                        A   B   C   D
first_index sec_index
idxKey0     newK0      A0  B0  C0  D0
idxKey1     newK1      A1  B1  C1  D1
idxKey2     newK2      A2  B2  C2  D2

In [141]:
# join 2 multi-index dfs with outer join (union)
multiindex_outer_df = left_df.join(right_df, how = "outer")
multiindex_outer_df

                         A    B   C   D
first_index sec_index
idxKey0     newK0       A0   B0  C0  D0
idxKey1     newK1       A1   B1  C1  D1
idxKey2     newK2       A2   B2  C2  D2
idxKey3     newK3      NaN  NaN  C3  D3

### Example: `.compare()` - show differences between 2 series or dataframes

In [143]:
main_df = pd.DataFrame(
     {
          "col1": ["a", "a", "b", "b", "a"],
          "col2": [1.0, 2.0, 3.0, np.nan, 5.0],
          "col3": [1.0, 2.0, 3.0, 4.0, 5.0]
     }
)
main_df

  col1  col2  col3
0    a   1.0   1.0
1    a   2.0   2.0
2    b   3.0   3.0
3    b   NaN   4.0
4    a   5.0   5.0

In [145]:
sim_but_diff_df = main_df.copy() # makes a copy of a df
sim_but_diff_df.loc[0, "col1"] = "c" # update index #0 col1 cell to now be the value "c"
sim_but_diff_df.loc[2, "col3"] = 4.0 # update index #2 col3 cell to value 4.0
sim_but_diff_df

  col1  col2  col3
0    c   1.0   1.0
1    a   2.0   2.0
2    b   3.0   4.0
3    b   NaN   4.0
4    a   5.0   5.0

In [ ]:
# now compare the similaries and differences between the two
# Only shows the differences
main_df.compare(sim_but_diff_df, keep_shape=True, result_names = ("self", "other"), )

  col1       col2       col3
  self other self other self other
0    a     c  NaN   NaN  NaN   NaN
1  NaN   NaN  NaN   NaN  NaN   NaN
2  NaN   NaN  NaN   NaN  3.0   4.0
3  NaN   NaN  NaN   NaN  NaN   NaN
4  NaN   NaN  NaN   NaN  NaN   NaN

In [ ]:
sim_but_diff_df.loc[4, "col3"] = np.nan # update index #4 col5 cell to value NaN
main_df.compare(sim_but_diff_df, keep_shape=True, result_names = ("self", "other"), )

  col1       col2       col3
  self other self other self other
0    a     c  NaN   NaN  NaN   NaN
1  NaN   NaN  NaN   NaN  NaN   NaN
2  NaN   NaN  NaN   NaN  3.0   4.0
3  NaN   NaN  NaN   NaN  NaN   NaN
4  NaN   NaN  NaN   NaN  5.0   NaN

In [154]:
# when keep_shape = False, only keeps row and columns that have differences
main_df.compare(sim_but_diff_df, keep_shape=False, result_names = ("df_main", "sim_but_diff"), )

     col1                 col3
  df_main sim_but_diff df_main sim_but_diff
0       a            c     NaN          NaN
2     NaN          NaN     3.0          4.0
4     NaN          NaN     5.0          NaN

## Reshaping and pivoting dataframes and series  
* `.pivot()` and `pandas.pivot_table()`
  * pivot() can only handle unique rows specified by index and columns. If you data contains duplicates, use pivot_table().
* `.stack()` and `.unstack()` - Pivot a column or row level to the opposite axis respectively.
* `.melt()` and `wide_to_long()` -  Unpivot a wide DataFrame to a long format
* `.crosstab()` - generate frequency tables of two or more factors and normalize to percent if wanted
* `.cut()` - Transform continuous variables to discrete, categorical values

### Example: `.pivot()` and `pandas.pivot_table()`

In [157]:
df2

             A          B    C  D        E    F  G         H      I     J
sample 1   2.0 2013-01-02  NaN  5     test  foo  2  0.168002   True   NaN
sample 2  10.0 2013-01-02  NaN  3    train  foo  6  0.836041  False  None
sample 1  10.0 2013-01-02  NaN  3  unknown  foo  6  0.725179  False  None
sample 2  10.0 2013-01-02  NaN  3    train  foo -2  0.972486  False   NaN
sample 3  10.0 2013-01-02  NaN  3    train  foo -5  0.981977  False   NaT
sample 4  10.0 2013-01-02  3.0  3     test  foo -5  0.685862   True  <NA>
sample 5   2.0 2013-01-02  NaN  3     test  foo  5  0.026497   True  None

In [160]:
df = pd.DataFrame(data = {
     "value": range(12),
     "variable": ["A"] * 3 + ["B"] * 3 + ["C"] * 3 + ["D"] * 3,
     "date": pd.to_datetime(["2020-01-03", "2020-01-04", "2020-01-05"] * 4)
     })
df

    value variable       date
0       0        A 2020-01-03
1       1        A 2020-01-04
2       2        A 2020-01-05
3       3        B 2020-01-03
4       4        B 2020-01-04
5       5        B 2020-01-05
6       6        C 2020-01-03
7       7        C 2020-01-04
8       8        C 2020-01-05
9       9        D 2020-01-03
10     10        D 2020-01-04
11     11        D 2020-01-05

In [ ]:
# useful when you need dfs to be condensed if they were in long/stack format before
pivoted = df.pivot(index = "date", columns="variable", values = "value")
pivoted

variable    A  B  C   D
date
2020-01-03  0  3  6   9
2020-01-04  1  4  7  10
2020-01-05  2  5  8  11

In [164]:
# same as above but if you omit value and you have multiple columns that can be value
# then it splits each possible column value into a separate index of hierarchical columns
df["value2"] = df["value"] * 2
pivoted_v2 = df.pivot(index = "date", columns="variable")
pivoted_v2

           value           value2
variable       A  B  C   D      A   B   C   D
date
2020-01-03     0  3  6   9      0   6  12  18
2020-01-04     1  4  7  10      2   8  14  20
2020-01-05     2  5  8  11      4  10  16  22

In [165]:
# if using the above, you can subset the multi-index/hierarchical column dataframes
pivoted_v2["value2"]

variable    A   B   C   D
date
2020-01-03  0   6  12  18
2020-01-04  2   8  14  20
2020-01-05  4  10  16  22

In [166]:
df2

             A          B    C  D        E    F  G         H      I     J
sample 1   2.0 2013-01-02  NaN  5     test  foo  2  0.168002   True   NaN
sample 2  10.0 2013-01-02  NaN  3    train  foo  6  0.836041  False  None
sample 1  10.0 2013-01-02  NaN  3  unknown  foo  6  0.725179  False  None
sample 2  10.0 2013-01-02  NaN  3    train  foo -2  0.972486  False   NaN
sample 3  10.0 2013-01-02  NaN  3    train  foo -5  0.981977  False   NaT
sample 4  10.0 2013-01-02  3.0  3     test  foo -5  0.685862   True  <NA>
sample 5   2.0 2013-01-02  NaN  3     test  foo  5  0.026497   True  None

In [ ]:
# since pivot_table has an aggregate function option, duplicates rows are allowd for the index as it will
# apply the aggregate function to the duplicates
pd.pivot_table(df2, index = "E", columns = "B", values = "D", aggfunc="mean")

B        2013-01-02
E
test       3.666667
train      3.000000
unknown    3.000000

In [170]:
pd.pivot_table(df2, index = "E", columns = "B", values = "D", aggfunc="sum")

B        2013-01-02
E
test             11
train             9
unknown           3

In [ ]:
# you can apply multiple aggregate functions and select multiple columns or indices
pd.pivot_table(df2, index = "E", columns = ["B"], values = ["D", "G"], aggfunc=["max", "mean", "sum"])

               max                  mean                   sum
                 D          G          D          G          D          G
B       2013-01-02 2013-01-02 2013-01-02 2013-01-02 2013-01-02 2013-01-02
E
test             5          5   3.666667   0.666667         11          2
train            3          6   3.000000  -0.333333          9         -1
unknown          3          6   3.000000   6.000000          3          6

### Example: `.stack()` and `.unstack()`

In [176]:
df2

             A          B    C  D        E    F  G         H      I     J
sample 1   2.0 2013-01-02  NaN  5     test  foo  2  0.168002   True   NaN
sample 2  10.0 2013-01-02  NaN  3    train  foo  6  0.836041  False  None
sample 1  10.0 2013-01-02  NaN  3  unknown  foo  6  0.725179  False  None
sample 2  10.0 2013-01-02  NaN  3    train  foo -2  0.972486  False   NaN
sample 3  10.0 2013-01-02  NaN  3    train  foo -5  0.981977  False   NaT
sample 4  10.0 2013-01-02  3.0  3     test  foo -5  0.685862   True  <NA>
sample 5   2.0 2013-01-02  NaN  3     test  foo  5  0.026497   True  None

In [180]:
# takes all columns and "stacks" them to have their own row entries
stacked_df = df2.stack() 
stacked_df

sample 1  A                    2.0
          B    2013-01-02 00:00:00
          C                    NaN
          D                      5
          E                   test
                      ...
sample 5  F                    foo
          G                      5
          H               0.026497
          I                   True
          J                   None
Length: 70, dtype: object

In [182]:
multiindex_inner_df

                        A   B   C   D
first_index sec_index
idxKey0     newK0      A0  B0  C0  D0
idxKey1     newK1      A1  B1  C1  D1
idxKey2     newK2      A2  B2  C2  D2

In [184]:
multidf_stacked = multiindex_inner_df.stack()
multidf_stacked

first_index  sec_index
idxKey0      newK0      A    A0
                        B    B0
                        C    C0
                        D    D0
idxKey1      newK1      A    A1
                        B    B1
                        C    C1
                        D    D1
idxKey2      newK2      A    A2
                        B    B2
                        C    C2
                        D    D2
dtype: str

In [ ]:
# important note, is you can only unstack if you have unique indices, so trying to unstack
# on the df2 object is not possible because the sample IDs used as indices are non-unique
# when multi-level indices are unstacked it default to unstack the last level
multidf_stacked.unstack()

                        A   B   C   D
first_index sec_index
idxKey0     newK0      A0  B0  C0  D0
idxKey1     newK1      A1  B1  C1  D1
idxKey2     newK2      A2  B2  C2  D2

In [ ]:
# to unstack the first level you can select the index number or call it by index name
# the default is level = -1 which is the last level
multidf_stacked.unstack(level = 0)

first_index idxKey0 idxKey1 idxKey2
sec_index
newK0     A      A0     NaN     NaN
          B      B0     NaN     NaN
          C      C0     NaN     NaN
          D      D0     NaN     NaN
newK1     A     NaN      A1     NaN
          B     NaN      B1     NaN
          C     NaN      C1     NaN
          D     NaN      D1     NaN
newK2     A     NaN     NaN      A2
          B     NaN     NaN      B2
          C     NaN     NaN      C2
          D     NaN     NaN      D2

In [187]:
multidf_stacked.unstack(level = 'first_index')

first_index idxKey0 idxKey1 idxKey2
sec_index
newK0     A      A0     NaN     NaN
          B      B0     NaN     NaN
          C      C0     NaN     NaN
          D      D0     NaN     NaN
newK1     A     NaN      A1     NaN
          B     NaN      B1     NaN
          C     NaN      C1     NaN
          D     NaN      D1     NaN
newK2     A     NaN     NaN      A2
          B     NaN     NaN      B2
          C     NaN     NaN      C2
          D     NaN     NaN      D2

### Example: `.melt()` and `.wide_to_long()`

In [189]:
horizontal_concat_df

     A          B    C  D      E    F phenotype status  temp
0  1.0 2013-01-02  1.0  3   test  foo        wt    low    54
1  1.0 2013-01-02  1.0  3  train  foo        ko    med    70
2  1.0 2013-01-02  1.0  3   test  foo        wt    low    70
3  1.0 2013-01-02  1.0  3  train  foo        ko   high    41
4  1.0 2013-01-02  1.0  3   test  foo        wt   high    58
5  1.0 2013-01-02  1.0  3  train  foo        ko    low    48
6  1.0 2013-01-02  1.0  3   test  foo        wt   high    46
7  1.0 2013-01-02  1.0  3  train  foo        ko    med    39

In [ ]:
# select a column to be the identifier variale and 
# all other columns are treated as variable names and their corresponding values
horizontal_concat_df.melt(id_vars=["phenotype"])

   phenotype variable value
0         wt        A   1.0
1         ko        A   1.0
2         wt        A   1.0
3         ko        A   1.0
4         wt        A   1.0
..       ...      ...   ...
59        ko     temp    41
60        wt     temp    58
61        ko     temp    48
62        wt     temp    46
63        ko     temp    39

[64 rows x 3 columns]

In [193]:
# now phenotype ans status are both identifiers and the remaining columns are variables
# with their matching corresponding values
horizontal_concat_df.melt(id_vars=["phenotype", "status"])

   phenotype status variable                value
0         wt    low        A                  1.0
1         ko    med        A                  1.0
2         wt    low        A                  1.0
3         ko   high        A                  1.0
4         wt   high        A                  1.0
5         ko    low        A                  1.0
6         wt   high        A                  1.0
7         ko    med        A                  1.0
8         wt    low        B  2013-01-02 00:00:00
9         ko    med        B  2013-01-02 00:00:00
10        wt    low        B  2013-01-02 00:00:00
11        ko   high        B  2013-01-02 00:00:00
12        wt   high        B  2013-01-02 00:00:00
13        ko    low        B  2013-01-02 00:00:00
14        wt   high        B  2013-01-02 00:00:00
15        ko    med        B  2013-01-02 00:00:00
16        wt    low        C                  1.0
17        ko    med        C                  1.0
18        wt    low        C                  1.0
19        ko   high        C                  1.0
20        wt   high        C                  1.0
21        ko    low        C                  1.0
22        wt   high        C                  1.0
23        ko    med        C                  1.0
24        wt    low        D                    3
25        ko    med        D                    3
26        wt    low        D                    3
27        ko   high        D                    3
28        wt   high        D                    3
29        ko    low        D                    3
30        wt   high        D                    3
31        ko    med        D                    3
32        wt    low        E                 test
33        ko    med        E                train
34        wt    low        E                 test
35        ko   high        E                train
36        wt   high        E                 test
37        ko    low        E                train
38        wt   high        E                 test
39        ko    med        E                train
40        wt    low        F                  foo
41        ko    med        F                  foo
42        wt    low        F                  foo
43        ko   high        F                  foo
44        wt   high        F                  foo
45        ko    low        F                  foo
46        wt   high        F                  foo
47        ko    med        F                  foo
48        wt    low     temp                   54
49        ko    med     temp                   70
50        wt    low     temp                   70
51        ko   high     temp                   41
52        wt   high     temp                   58
53        ko    low     temp                   48
54        wt   high     temp                   46
55        ko    med     temp                   39

### Example: `pandas.crosstab()` to summarize frequencies

In [ ]:
# must be two series
# counts the number of occurences between the two series
frequencies_df = pd.crosstab(horizontal_concat_df['status'], horizontal_concat_df['phenotype'], 
                             dropna = True,  
                             normalize= False)
frequencies_df

phenotype  ko  wt
status
high        1   2
low         1   2
med         2   0

In [ ]:
# must be two series
# fraction of all occurences between the two series (multiply by 100 to get percent)
frequencies_perc_df = pd.crosstab(horizontal_concat_df['status'], horizontal_concat_df['phenotype'], 
                             dropna = True,  
                             normalize= True)
frequencies_perc_df

phenotype     ko    wt
status
high       0.125  0.25
low        0.125  0.25
med        0.250  0.00

In [ ]:
# must be two series
# fraction of column occurences between the two series (multiply by 100 to get percent)
# this time each column will total to 100% so normalized by column
frequencies_norm_by_col_df = pd.crosstab(horizontal_concat_df['status'], horizontal_concat_df['phenotype'], 
                             dropna = True,  
                             normalize= "columns")
frequencies_norm_by_col_df

phenotype    ko   wt
status
high       0.25  0.5
low        0.25  0.5
med        0.50  0.0

In [199]:
# must be two series
# fraction of row occurences between the two series (multiply by 100 to get percent)
# this time each row will total to 100% so normalized by row
frequencies_norm_by_row_df = pd.crosstab(horizontal_concat_df['status'], horizontal_concat_df['phenotype'], 
                             dropna = True,  
                             normalize= "index")
frequencies_norm_by_row_df

phenotype        ko        wt
status
high       0.333333  0.666667
low        0.333333  0.666667
med        1.000000  0.000000

### Example: `pandas.cut()` - grouping continuous values into discrete/categorical bins

In [201]:
horizontal_concat_df

     A          B    C  D      E    F phenotype status  temp
0  1.0 2013-01-02  1.0  3   test  foo        wt    low    54
1  1.0 2013-01-02  1.0  3  train  foo        ko    med    70
2  1.0 2013-01-02  1.0  3   test  foo        wt    low    70
3  1.0 2013-01-02  1.0  3  train  foo        ko   high    41
4  1.0 2013-01-02  1.0  3   test  foo        wt   high    58
5  1.0 2013-01-02  1.0  3  train  foo        ko    low    48
6  1.0 2013-01-02  1.0  3   test  foo        wt   high    46
7  1.0 2013-01-02  1.0  3  train  foo        ko    med    39

In [ ]:
# create 3 equal width bins and treat them as categories
pd.cut(horizontal_concat_df['temp'], bins = 3)

0    (49.333, 59.667]
1      (59.667, 70.0]
2      (59.667, 70.0]
3    (38.969, 49.333]
4    (49.333, 59.667]
5    (38.969, 49.333]
6    (38.969, 49.333]
7    (38.969, 49.333]
Name: temp, dtype: category
Categories (3, interval[float64, right]): [(38.969, 49.333] < (49.333, 59.667] < (59.667, 70.0]]

In [205]:
# create custum bin width and treat them as categories
pd.cut(horizontal_concat_df['temp'], bins = [0, 54, 100])

0      (0, 54]
1    (54, 100]
2    (54, 100]
3      (0, 54]
4    (54, 100]
5      (0, 54]
6      (0, 54]
7      (0, 54]
Name: temp, dtype: category
Categories (2, interval[int64, right]): [(0, 54] < (54, 100]]

## Working with strings and text in pandas dataframes and series  

For a full list of all string functions available see: https://pandas.pydata.org/docs/user_guide/text.html#method-summary

Of important note, `dtype="str"` will set NA values using `np.nan`, while `dtype="string"` will use `pandas.NA` to set NA values.  
* `.str.lower()`
  * convert a series to all lower case  
* `.str.upper()`
  * convert a series to all capitals
* `.str.len()`
  * get the length of each string in a cell of a series
* `.str.strip()`, `.str.rstrip()`, `.str.lstrip()`
  * clean up strings of whitespace
* `.str.replace()`
  * find and replace all matches with new string, supports regex
* `.str.split()`, `.str.rsplit()`
  * split a string in a series and then it returns a list per cell split for the series, which could technically be transformed to new row instanace for each split using `explode()` see: https://pandas.pydata.org/docs/user_guide/reshaping.html#explode
  * the `.str.rsplit()` method is the same as `.str.split()` but starts the string splitting in the reverse direction, which does change the outcome if you set a max number of splits
* `.str.removeprefix()` and `.str.removesuffix()`
* `.str.cat()` 
  * concatenate the contents of a Series or Index
* `.str.extract()` and `.str.extractall()`
  * extract the first match substring in a Series using `.extract()` or extat all matches (`.extractall()`) 
* `.str.contains()`  
  * returns a `bool` of whether the pattern in you are searching for is found in each string of your series

## Group by: split-apply-combine
see: https://pandas.pydata.org/docs/user_guide/text.html#method-summary

Behavior is similar to R tidyverse groupby, where on the backend you are splitting the dataframe into smaller non-visible dataframes, applying a function on those to summarize the data per group, and then squishing the data back together

To see all aggregation methods available that can be applied to groupby functions:  
* https://pandas.pydata.org/docs/user_guide/groupby.html#built-in-aggregation-methods

In [206]:
speeds = pd.DataFrame(
     [
          ("bird", "Falconiformes", 389.0),
          ("bird", "Psittaciformes", 24.0),
          ("mammal", "Carnivora", 80.2),
          ("mammal", "Primates", np.nan),
          ("mammal", "Carnivora", 58),
     ],
     index = ["falcon", "parrot", "lion", "monkey", "leopard"],
     columns = ("class", "order", "max_speed")
)

speeds

          class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [208]:
class_grouped = speeds.groupby(by = "class", dropna=True)
class_grouped

In [ ]:
# since we grouped by class, we get the sum of all max_speed values per class
class_grouped['max_speed'].sum()

class
bird      413.0
mammal    138.2
Name: max_speed, dtype: float64

In [212]:
# since we grouped by class, we get the mean of all max_speed values split by class
class_grouped['max_speed'].mean()

class
bird      206.5
mammal     69.1
Name: max_speed, dtype: float64

In [ ]:
# You can also group by index levels (row names) and indicies that have duplicate names will be treated
# as the same group
df2

             A          B    C  D        E    F  G         H      I     J
sample 1   2.0 2013-01-02  NaN  5     test  foo  2  0.168002   True   NaN
sample 2  10.0 2013-01-02  NaN  3    train  foo  6  0.836041  False  None
sample 1  10.0 2013-01-02  NaN  3  unknown  foo  6  0.725179  False  None
sample 2  10.0 2013-01-02  NaN  3    train  foo -2  0.972486  False   NaN
sample 3  10.0 2013-01-02  NaN  3    train  foo -5  0.981977  False   NaT
sample 4  10.0 2013-01-02  3.0  3     test  foo -5  0.685862   True  <NA>
sample 5   2.0 2013-01-02  NaN  3     test  foo  5  0.026497   True  None

In [ ]:
# You can also group by index levels (row names) and indicies that have duplicate names will be treated
# as the same group; level is the index name or position if you have multilevel indices
grouped_df2_by_rownames = df2.groupby(level = 0)
grouped_df2_by_rownames

In [217]:
# You can also group by index levels (row names) and indicies that have duplicate names will be treated
# as the same group; level is the index name or position if you have multilevel indices
grouped_df2_by_rownames['A'].sum()

sample 1    12.0
sample 2    20.0
sample 3    10.0
sample 4    10.0
sample 5     2.0
Name: A, dtype: float64

In [ ]:
# count the number of occurences of column E
grouped_df2_by_rownames['E'].count()

sample 1    2
sample 2    2
sample 3    1
sample 4    1
sample 5    1
Name: E, dtype: int64

In [ ]:
# you can apply filters to each group as well
# this will filter samples where the sum of the entire sample group (since sample is level = 0),
# is negative
# filter expression is if the value returns True, you keep it, and throw out any rows that are False
df2.groupby(level = 0).filter(lambda x: x['G'].sum() >= 0)

             A          B   C  D        E    F  G         H      I     J
sample 1   2.0 2013-01-02 NaN  5     test  foo  2  0.168002   True   NaN
sample 2  10.0 2013-01-02 NaN  3    train  foo  6  0.836041  False  None
sample 1  10.0 2013-01-02 NaN  3  unknown  foo  6  0.725179  False  None
sample 2  10.0 2013-01-02 NaN  3    train  foo -2  0.972486  False   NaN
sample 5   2.0 2013-01-02 NaN  3     test  foo  5  0.026497   True  None

In [ ]:
# group the dataframe by phenotype first, so there will be a wt dataframe and a ko
# dataframe.  Then take teh average temp of just wildtype and the average temp of just ko
# remove group if the mean temp of the group is less than 50.
# filter expression is if the value returns True, you keep it, and throw out any rows that are False
horizontal_concat_df.groupby(by = "phenotype").filter(lambda x:x["temp"].mean() > 50)

     A          B    C  D     E    F phenotype status  temp
0  1.0 2013-01-02  1.0  3  test  foo        wt    low    54
2  1.0 2013-01-02  1.0  3  test  foo        wt    low    70
4  1.0 2013-01-02  1.0  3  test  foo        wt   high    58
6  1.0 2013-01-02  1.0  3  test  foo        wt   high    46

## Sparse data structures in the context of pandas

The definition of "sparse" in pandas, does not necessarily mean it contains mostly zeros, but rather it is the pandas way of compressing data frames to save on memory.  NaN values are omitted from being stored in memory.  However if 0 values should be used instead, one can specify 0 is the sparse value by setting `fill_value` to be 0 instead of NaN (np.NaN)

In pandas, sparsity is column-based: each column is a sparse Series backed by a SparseArray. A “sparse DataFrame” is therefore just a DataFrame whose columns use sparse dtypes.

https://pandas.pydata.org/docs/user_guide/sparse.html#sparse-data-structures

In [241]:
rand_array = np.random.randn(10)
rand_array[2:-2] = np.nan
rand_array

array([-0.61165985, -0.35607529,         nan,         nan,         nan,
               nan,         nan,         nan, -0.40216597, -0.53176578])

In [244]:
# memory used in bytes of a single object
rand_array.nbytes

80

In [246]:
# the dtype of Sparse[float64, nan] means that nans are ommited from being
# stored in memory; non-nan values are stored as type float64
sparse_rand_array = pd.Series(pd.arrays.SparseArray(rand_array))
sparse_rand_array

0    -0.61166
1   -0.356075
2         NaN
3         NaN
4         NaN
5         NaN
6         NaN
7         NaN
8   -0.402166
9   -0.531766
dtype: Sparse[float64, nan]

In [ ]:
# number of bytes stored in memory of the same array but in sparse format
sparse_rand_array.nbytes

48

In [251]:
# testing sparse matrix on heavy 0 matrix
rand_array = np.random.randn(50)
rand_array[5:-5] = 0
rand_array

array([ 0.27978121,  0.07927471,  1.13500626,  0.14610693, -2.76233486,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       -0.31287238, -1.33066722, -0.82919909, -0.14723315, -0.09449198])

In [252]:
rand_array.nbytes

400

In [ ]:
# the dtype of Sparse[float64, 0] means that 0 are ommited from being
# stored in memory; non-zero vpdalues are stored as type float64
sparse_rand_array = pd.Series(.arrays.SparseArray(rand_array, fill_value = 0))
sparse_rand_array

0     0.279781
1     0.079275
2     1.135006
3     0.146107
4    -2.762335
5            0
6            0
7            0
8            0
9            0
10           0
11           0
12           0
13           0
14           0
15           0
16           0
17           0
18           0
19           0
20           0
21           0
22           0
23           0
24           0
25           0
26           0
27           0
28           0
29           0
30           0
31           0
32           0
33           0
34           0
35           0
36           0
37           0
38           0
39           0
40           0
41           0
42           0
43           0
44           0
45   -0.312872
46   -1.330667
47   -0.829199
48   -0.147233
49   -0.094492
dtype: Sparse[float64, 0]

In [255]:
sparse_rand_array.nbytes

120